# Generated by Django 2.2 on 2019-04-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuzu_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='liked_users',
            field=models.ManyToManyField(related_name='liked_images', related_query_name='liked_image', to='yuzu_gallery.GalleryUser'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
